### PR TITLE
fix: move updated github data directly to docs

### PR DESCRIPTION
**Pull request by marianfoo**
move updated GitHub Data directly to docs folder

### CODE REVIEW

**Comment by IObert** [comment]
Ah, sorry. This was a misunderstand. I think the json files should be written to both places (frontend and docs). Otherwise, I'll reset the value with every commit (as this triggers an action that overrides docs again)

**Comment by IObert** [comment]
Also, please rename the job in line 9 to something different

**Comment by marianfoo** [comment]
@IObert implemented your requests

**Comment by IObert** [comment]
Awesome, thanks!

**Comment by marianfoo** [comment]
Perfect, let´s see if it works tomorrow

**Pull request merged**
